// fallow-ignore-file unused-file
/**
 * Scoreboard generator — runs UNDER vitest (the repo has no tsx/ts-node).
 *
 * This file is deliberately NOT named `*.test.ts`, so the default `npm test`
 * (`vitest run`, include `src/**\/*.test.ts`) does not pick it up — no scoreboard
 * write on every test run. Regenerate on demand with `npm run corpus:report`.
 *
 * It imports the SAME `allCases()` the runner uses, computes per-dimension and overall
 * tallies, and writes `.scratch/import-format-normalization/scoreboard.md`.
 *
 * Capability % = passing / (passing + aspirational). `characterized` cases pin current
 * behaviour and do not move the capability number. Regression is NOT on the scoreboard
 * — it is enforced by the suite (`corpus.test.ts`) going red.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { test } from 'vitest'
import { allCases } from './loader'
import type { CorpusCase, Status } from './types'

interface Tally {
  passing: number
  characterized: number
  aspirational: number
}

function emptyTally(): Tally {
  return { passing: 0, characterized: 0, aspirational: 0 }
}

function bump(tally: Tally, status: Status): void {
  tally[status] += 1
}

function capability(tally: Tally): string {
  const denom = tally.passing + tally.aspirational
  if (denom === 0) return 'n/a'
  return `${Math.round((tally.passing / denom) * 100)}%`
}

function row(label: string, tally: Tally): string {
  return `| ${label} | ${tally.passing} | ${tally.characterized} | ${tally.aspirational} | ${capability(tally)} |`
}

function buildScoreboard(cases: CorpusCase[]): string {
  const byDim = new Map<string, Tally>()
  const overall = emptyTally()

  for (const c of cases) {
    if (!byDim.has(c.dim)) byDim.set(c.dim, emptyTally())
    bump(byDim.get(c.dim)!, c.status)
    bump(overall, c.status)
  }

  const dims = [...byDim.keys()].sort()
  const lines: string[] = []
  lines.push('# Normalization Conformance scoreboard')
  lines.push('')
  lines.push('Generated by `npm run corpus:report`. Do not edit by hand — regenerated from')
  lines.push('`src/shared/__tests__/normalization-corpus/` cases. This file lives in the')
  lines.push('gitignored `.scratch/` tree.')
  lines.push('')
  lines.push(`Generated: ${new Date().toISOString()}`)
  lines.push('')
  lines.push('Capability % = passing / (passing + aspirational). `char` (characterized) pins')
  lines.push('current behaviour and does not move capability. Regression is enforced by the')
  lines.push('suite going red, not shown here.')
  lines.push('')
  lines.push('| dim | pass | char | asp | capability% |')
  lines.push('| --- | ---: | ---: | --: | ----------: |')
  for (const dim of dims) {
    lines.push(row(dim, byDim.get(dim)!))
  }
  lines.push(row('**OVERALL**', overall))
  lines.push('')
  return lines.join('\n')
}

test('generate scoreboard', () => {
  const outPath = resolve(process.cwd(), '.scratch/import-format-normalization/scoreboard.md')
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, buildScoreboard(allCases()), 'utf8')
  // eslint-disable-next-line no-console
  console.log(`[corpus:report] wrote ${outPath}`)
})
